if [[ -e "${HOME}"/.xinitrc_before ]]
then
    . "${HOME}"/.xinitrc_before
fi

if which "${COMPMGR}"
then
    "${COMPMGR}" &disown
fi

if [[ -e "${HOME}"/.xinitrc_after ]]
then
    source "${HOME}"/.xinitrc_after
fi

if which "${FCITX}"
then
    "${FCITX}" &disown
fi

"${WM}"
